version: '3.3'
services:
  server:
    build:
      context: ./
      dockerfile: ./server-3.x/Dockerfile
    ports:
      - '5001:5001'

  client:
    build:
      context: ./
      dockerfile: ./client-2.x/Dockerfile

    depends_on:
      - server

    environment:
      - GRPC_HOST=server
      - GRPC_PORT=50051
